logging:
   path: "/var/log/count.log"
   level: "info"
customer:
  id: 1
  name: "El pentagono"
database:
  engine: 'mysql' #Avaiable database engines at http://docs.sqlalchemy.org/en/latest/core/engines.html
  server: 'db-vader.c9m0fo1qyj7d.us-west-2.rds.amazonaws.com'
  database: 'people_recognition'
  username: 'root'
  password: 'rootroot'
cameras:
  - id: 1
    source: 'http://96.10.1.168/axis-cgi/mjpg/video.cgi?resolution=640x480'
    description: "Main Camera"
    in_area:
      - '0;50'
      - '0;150'
      - '640;150'
      - '640;50'
    out_area:
      - '0;400'
      - '0;300'
      - '640;300'
      - '640;400'
    critical_area:
      - '0;150'
      - '640;150'
      - '640;300'
      - '0;300'
    max_person_age: 5
    detection_area: 600
  - id: 2
    source: 'http://plazacam.studentaffairs.duke.edu/axis-cgi/mjpg/video.cgi?resolution=640x480'
    description: "University"
    in_area:
      - '0;50'
      - '0;200'
      - '640;200'
      - '640;50'
    out_area:
      - '0;400'
      - '0;300'
      - '640;300'
      - '640;400'
    critical_area:
      - '0;200'
      - '640;200'
      - '640;300'
      - '0;300'
    max_person_age: 5
    detection_area: 150