cameras:
  - id: 1
    source: 0
    description: "Main Camera"
    in_area:
      - '0;0'
      - '0;120'
      - '640;120'
      - '640;0'
    out_area:
      - '0;480'
      - '0;360'
      - '640;360'
      - '640;480'
    critical_area:
      - '0;120'
      - '640;120'
      - '640;360'
      - '0;360'
    max_person_age: 5
    detection_area: 300
